//
// Generated file, do not edit! Created by nedtool 5.6 from packet/ACK.msg.
//

#ifndef __ACK_M_H
#define __ACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>packet/ACK.msg:18</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * message ACK
 * {
 *     int srcTor;
 *     int destTor;
 * }
 * </pre>
 */
class ACK : public ::omnetpp::cMessage
{
  protected:
    int srcTor;
    int destTor;

  private:
    void copy(const ACK& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ACK&);

  public:
    ACK(const char *name=nullptr, short kind=0);
    ACK(const ACK& other);
    virtual ~ACK();
    ACK& operator=(const ACK& other);
    virtual ACK *dup() const override {return new ACK(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrcTor() const;
    virtual void setSrcTor(int srcTor);
    virtual int getDestTor() const;
    virtual void setDestTor(int destTor);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ACK& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ACK& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ACK_M_H

