//
// Generated file, do not edit! Created by nedtool 5.6 from packet/PFC.msg.
//

#ifndef __PFC_M_H
#define __PFC_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>packet/PFC.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message PFC
 * {
 *     int priorty;
 *     bool PAUSE;
 * }
 * </pre>
 */
class PFC : public ::omnetpp::cMessage
{
  protected:
    int priorty;
    bool PAUSE;

  private:
    void copy(const PFC& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PFC&);

  public:
    PFC(const char *name=nullptr, short kind=0);
    PFC(const PFC& other);
    virtual ~PFC();
    PFC& operator=(const PFC& other);
    virtual PFC *dup() const override {return new PFC(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPriorty() const;
    virtual void setPriorty(int priorty);
    virtual bool getPAUSE() const;
    virtual void setPAUSE(bool PAUSE);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PFC& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PFC& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PFC_M_H

