//
// Generated file, do not edit! Created by nedtool 5.6 from packet/Setup.msg.
//

#ifndef __SETUP_M_H
#define __SETUP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>packet/Setup.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Setup
 * {
 *     int input;
 *     int output;
 *     int bufferId;
 *     bool flag;
 * }
 * </pre>
 */
class Setup : public ::omnetpp::cMessage
{
  protected:
    int input;
    int output;
    int bufferId;
    bool flag;

  private:
    void copy(const Setup& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Setup&);

  public:
    Setup(const char *name=nullptr, short kind=0);
    Setup(const Setup& other);
    virtual ~Setup();
    Setup& operator=(const Setup& other);
    virtual Setup *dup() const override {return new Setup(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getInput() const;
    virtual void setInput(int input);
    virtual int getOutput() const;
    virtual void setOutput(int output);
    virtual int getBufferId() const;
    virtual void setBufferId(int bufferId);
    virtual bool getFlag() const;
    virtual void setFlag(bool flag);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Setup& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Setup& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SETUP_M_H

